import * as React from 'react';
export type IconName =
  | "Arrow16"
  | "ArrowDown24"
  | "ArrowHeader"
  | "Bookmarks24Solid"
  | "Clips24Solid"
  | "Documents24Solid"
  | "Earth24"
  | "Friends24Solid"
  | "Games24Solid"
  | "Goods24Solid"
  | "Groups24Solid"
  | "HeadNotify24Solid"
  | "Home24Solid"
  | "HugeIconBusinessSolidBriefcase"
  | "HugeIconBusinessSolidChart"
  | "HugeIconBusinessSolidTarget"
  | "HugeIconCommunicationSolidBroadcast"
  | "HugeIconCommunicationSolidCalling"
  | "HugeIconCommunicationSolidMail"
  | "HugeIconFilesAndFolder"
  | "HugeIconFinanceAndPayment"
  | "HugeIconInterfaceSolidBoard"
  | "HugeIconInterfaceSolidCheck"
  | "HugeIconInterfaceSolidGlobe"
  | "HugeIconInterfaceSolidHome"
  | "HugeIconInterfaceSolidTicket"
  | "HugeIconMultimediaAndAudio"
  | "HugeIconSocialSolidTiktok"
  | "HugeIconSocialSolidYoutube"
  | "HugeIconUserSolidUser"
  | "Likes24"
  | "MessageCircle24"
  | "Messages24Solid"
  | "MessagesSquare24"
  | "More24"
  | "Music24Solid"
  | "News24Solid"
  | "Notification24"
  | "Pay24Solid"
  | "Phone24"
  | "Photos24Solid"
  | "PlayerBack24Solid"
  | "PlayerNext24Solid"
  | "PlayerPlay24Solid"
  | "Point24"
  | "Search16"
  | "Share24"
  | "TablerIconAddressBook"
  | "TablerIconBrandInstagram"
  | "TablerIconBrandSpotify"
  | "TablerIconBrandTelegram"
  | "TablerIconBrandTiktok"
  | "TablerIconBrandVk"
  | "TablerIconBrandYoutube"
  | "TablerIconFlame"
  | "TablerIconMail"
  | "TablerIconMailForward"
  | "TablerIconMailOpened"
  | "TablerIconMusic"
  | "TablerIconNews"
  | "TablerIconPhoneCall"
  | "TablerIconPlayerTrackNext"
  | "TablerIconPlaylist"
  | "TablerIconQuestionMark"
  | "TablerIconUser"
  | "TablerIconUsers"
  | "TablerIconVinyl"
  | "Text24"
  | "Video24Solid"
  | "Views16";
export interface IconProps extends React.SVGProps<SVGSVGElement> {
  name: IconName;
  size?: number | string;
}
export declare const Icon: React.FC<IconProps>;
export default Icon;
